// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package hotel

import (
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func ProvideRouter(db *gorm.DB) Router {
	repository := NewSqliteRepository(db)
	service := NewHotelService(repository)
	delivery := NewHttpDelivery(service)
	router := NewRouter(delivery)
	return router
}
